import { Platform, StyleSheet } from 'react-native';
import { COLORS } from '../../assets/theme/dark';

export const KycStyles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    flex: 1,
    paddingVertical: 20,
    paddingHorizontal: 15,
  },
  titleText: {
    color: '#5f6671',
    fontSize: 18,
    marginVertical: 10,
  },
  inputView: {
    marginTop: 10,
  },
  successDesc: {
    color: '#878899',
    marginTop: 10,
    width: 280,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
  },
  reviewDesc: {
    color: '#878899',
    marginTop: 10,
    width: 280,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
  },
  disbaleExpBtn: {
    width: 150,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 5,
  },
  exploreTxt: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  exploreBtn: {
    backgroundColor: '#4574F5',
    width: 150,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 5,
  },
  gotoExchange: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  underText: { color: 'white', alignSelf: 'center' },
  underView: { alignSelf: 'center', margin: 10 },
  underMain: { flex: 1, justifyContent: 'center' },
  successText: { color: 'white', alignSelf: 'center' },
  successView: { alignSelf: 'center', margin: 10 },
  successMain: { flex: 1, justifyContent: 'center' },
  kycMain: { flex: 1, justifyContent: 'center' },
  KycLogOut: { textAlign: 'center', fontSize: 16 },
  kycPageMain: { backgroundColor: '#fff', height: "100%",paddingBottom:Platform.OS == 'android' ? 175 : 90},
  closeKycPage:{backgroundColor:"#fff",alignItems:"flex-end",marginTop:Platform.OS == 'android' ? 40 : 0},
  veriText: { color: 'white', alignSelf: 'center' },
  veriRequired: { alignSelf: 'center', margin: 10 },
  closTxt:{color:'black',fontSize:18,fontWeight:"600",padding:10},
  veriDesc: {
    color: '#878899',
    marginTop: 10,
    width: 280,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
  },
  clossBtn: { position: 'absolute', right: 20, top: 20 },
  reasonFailed: {
    color: '#878899',
    marginTop: 10,
    width: 280,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
  },
  clossBTN: { position: 'absolute', right: 20, top: 20 },
  KycFailed: { flex: 1, justifyContent: 'center' },
  reiniKycKyb: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  textBTN: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  viewTouch: {
    backgroundColor: '#4574F5',
    width: 150,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 5,
  },
  btnReinitiate: {
    color: '#878899',
    marginTop: 10,
    width: 280,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
  },
  VeriFFAiled: { alignSelf: 'center', margin: 10 },
  kyckybBtn: {
    backgroundColor: '#4574F5',
    width: 150,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 5,
  },
  kyckybMain: { flex: 1, justifyContent: 'center' },
  verifailed: { alignSelf: 'center', margin: 10 },
  touchBtn: {
    backgroundColor: '#4574F5',
    width: 150,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 5,
  },
  startBtn: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  mainCont: {
    flex: 1,
    justifyContent: 'center'
  },
  clossBtn: { position: 'absolute', right:Platform.OS == 'android' ? 30 : 20, top:Platform.OS == 'android' ? 60 : 20 },
  input: {
    borderWidth: 1,
    borderColor: '#dcddf2',
    height: 60,
    borderRadius: 5,
    fontSize: 20,
    padding: 10,
    backgroundColor: '#f7f8fd',
    color: 'black',
  },
  proceedButton: {
    marginTop: 20,
    alignSelf: 'center',
    backgroundColor: '#3b65d7',
    padding: 20,
    width: '95%',
    borderRadius: 5,
    alignItems: 'center',
  },
  disableButton:{    
    marginTop: 20,
    alignSelf: 'center',
    backgroundColor: 'grey',
    padding: 20,
    width: '95%',
    borderRadius: 5,
    alignItems: 'center'
  },
  logoutButton: {
    marginTop: 20,
    alignSelf: 'center',
    backgroundColor: '#f3f3f3',
    padding: 20,
    width: '95%',
    borderRadius: 5,
  },
  errorMessage: {
    color: COLORS['color-red'],
    fontWeight: '500',
  },
  logout: {
    marginVertical: 8,
    alignSelf: 'center',
    borderColor: '#dcddf2',
    borderWidth: 2,
    borderRadius: 8,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    width: '92%',
  },
  kybMain:{flex: 1, justifyContent: 'center'},
  kybClose:{position: 'absolute', right: 20, top: 20},
  kybFailed:{alignSelf: 'center', margin: 10},
  failText:{color: 'white', alignSelf: 'center'},
  kybDesc:{
    color: '#878899',
    marginTop: 10,
    width: 280,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
  },
  kybBtnView:{
    backgroundColor: COLORS['primary-dark'],
    width: 150,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 5,
  },
  reiniText:{
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  }
});
