import {StyleSheet} from 'react-native';
import {COLORS} from '../../../../assets';

export const profileDetailStyles = StyleSheet.create({
  containerHeight: {
    alignItems: 'center',
    flex: 0.89,
    width: '100%',
    backgroundColor: COLORS['bg-100-dark'],
  },
  mainContainer: {
    width: '100%',
    flex: 0.98,
  },
  container: {
    height: 150,
    marginLeft: -16,
    marginRight: -16,
    marginTop: -50,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  contain: {
    backgroundColor: COLORS['bg-80-dark'],
    width: 100,
    height: 100,
    position: 'absolute',
    top: 100,
    borderRadius: 100,
    borderWidth: 2,
    borderColor: COLORS['bg-100-dark'],
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    width: 100,
    height: 100,
    borderRadius: 100,
  },
  name: {
    fontSize: 24,
    fontWeight: '600',
    color: COLORS['white'],
  },
  nameContain: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 60,
    marginBottom: 12,
  },
  fullName: {
    color: COLORS['white'],
    fontSize:16,
    fontWeight: '700',
    textAlign:"center"
  },
  email: {
    color: COLORS['font-color-light'],
    fontSize: 14,
    fontWeight: '500',
    marginTop: 4,
  },
  mobile: {
    color: "#878C99",
    fontSize: 12,
    fontWeight: '500',
    marginTop: 4,
  },
  AccountID: {
    color: "#878C99",
    fontSize: 12,
    fontWeight: '500',
    marginTop: 4,
    textAlign:"center"
  },
  listContainer: {
    flex: 1,
    width: '100%',
    justifyContent: 'space-around',
    paddingVertical: 10,
  },
  list: {
    width: '100%',
    height: 66,
    borderBottomWidth: 1,
    borderBottomColor: COLORS['color-border-dark-100'],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  selectedAsset: {
    borderColor: COLORS['color-orange'],
    borderWidth: 1,
    borderBottomColor: COLORS['color-orange'],
    borderRadius: 12,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 0.7,
  },
  icon: {flex: 0.1},
  title: {flex: 0.8},
  titleTxt: {
    fontSize: 14,
    fontWeight: '600',
    left: 16,
  },
  valueContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderTopColor: COLORS['input-border-dark'],
    borderTopWidth: 1,
    paddingVertical: 15,
  },
  key: {
    color: COLORS['font-color-light'],
    fontSize: 14,
    fontWeight: '500',
  },
  value: {
    flex: 0.8,
    textAlign: 'right',
    color: COLORS['white'],
    fontSize: 14,
    fontWeight: '500',
  },
  edit: {
    width: 40,
    height: 40,
    backgroundColor: COLORS['primary-light'],
    left: '7%',
    top: '35%',
    borderRadius: 50,
    justifyContent: 'center',
  },
  editIcon: {alignSelf: 'center'},
  editImageView: {
    position: 'absolute',
    padding: 10,
    backgroundColor: 'red',
    alignSelf: 'flex-end',
    bottom: 10,
    borderRadius: 50,
  },
  verifiedImage: {
    width: 16,
    height: 16,
  },
  editEmailButton: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    marginLeft: 10,
    borderBottomWidth: 1,
  },
  verifyButton: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    marginLeft: -22,
    borderBottomWidth: 1,
  },
  userDetailsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  profileImage: {width: 40, height: 40, borderRadius: 50},
  txtWrapper: {marginLeft: 16},
  txtName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS['color-orange'],
  },
  txtId: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS['font-color-light'],
  },
});
