export const State_array = [
  {code: 'AL', label: 'Alabama', value: 'AL'},
  {code: 'AK', label: 'Alaska', value: 'AK'},
  {code: 'AZ', label: 'Arizona', value: 'AZ'},
  {code: 'AR', label: 'Arkansas', value: 'AR'},
  {code: 'CA', label: 'California', value: 'CA'},
  {code: 'CO', label: 'Colorado', value: 'CO'},
  {code: 'CT', label: 'Connecticut', value: 'CT'},
  {code: 'DE', label: 'Delaware', value: 'DE'},
  {code: 'DC', label: 'District Of Columbia', value: 'DC'},
  {code: 'FL', label: 'Florida', value: 'FL'},
  {code: 'GA', label: 'Georgia', value: 'GA'},
  {code: 'HI', label: 'Hawaii', value: 'HI'},
  {code: 'ID', label: 'Idaho', value: 'ID'},
  {code: 'IL', label: 'Illinois', value: 'IL'},
  {code: 'IN', label: 'Indiana', value: 'IN'},
  {code: 'IA', label: 'Iowa', value: 'IA'},
  {code: 'KS', label: 'Kansas', value: 'KS'},
  {code: 'KY', label: 'Kentucky', value: 'KY'},
  {code: 'LA', label: 'Louisiana', value: 'LA'},
  {code: 'ME', label: 'Maine', value: 'ME'},
  {code: 'MD', label: 'Maryland', value: 'MD'},
  {code: 'MA', label: 'Massachusetts', value: 'MA'},
  {code: 'MI', label: 'Michigan', value: 'MI'},
  {code: 'MN', label: 'Minnesota', value: 'MN'},
  {code: 'MS', label: 'Mississippi', value: 'MS'},
  {code: 'MO', label: 'Missouri', value: 'MO'},
  {code: 'MT', label: 'Montana', value: 'MT'},
  {code: 'NE', label: 'Nebraska', value: 'NE'},
  {code: 'NV', label: 'Nevada', value: 'NV'},
  {code: 'NH', label: 'New Hampshire', value: 'NH'},
  {code: 'NJ', label: 'New Jersey', value: 'NJ'},
  {code: 'NM', label: 'New Mexico', value: 'NM'},
  {code: 'NY', label: 'New York', value: 'NY'},
  {code: 'NC', label: 'North Carolina', value: 'NC'},
  {code: 'ND', label: 'North Dakota', value: 'ND'},
  {code: 'OH', label: 'Ohio', value: 'OH'},
  {code: 'OK', label: 'Oklahoma', value: 'OK'},
  {code: 'OR', label: 'Oregon', value: 'OR'},
  {code: 'PA', label: 'Pennsylvania', value: 'PA'},
  {code: 'RI', label: 'Rhode Island', value: 'RI'},
  {code: 'SC', label: 'South Carolina', value: 'SC'},
  {code: 'SD', label: 'South Dakota', value: 'SD'},
  {code: 'TN', label: 'Tennessee', value: 'TN'},
  {code: 'TX', label: 'Texas', value: 'TX'},
  {code: 'UT', label: 'Utah', value: 'UT'},
  {code: 'VT', label: 'Vermont', value: 'VT'},
  {code: 'VA', label: 'Virginia', value: 'VA'},
  {code: 'WA', label: 'Washington', value: 'WA'},
  {code: 'WV', label: 'West Virginia', value: 'WV'},
  {code: 'WI', label: 'Wisconsin', value: 'WI'},
  {code: 'WY', label: 'Wyoming', value: 'WY'},
];
