import {StyleSheet, Platform} from 'react-native';
import {COLORS} from '../../../../assets';

export const coOwnersStyles = StyleSheet.create({
  wrapper: {flex: 1},
  mainContainer: {
    paddingHorizontal: 12,
    marginBottom: Platform.OS === 'android' ? 115 : 70,
  },
  container: {
    marginTop: 10,
    height: 70,
    borderRadius: 8,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  secondColomn: {paddingBottom: 4, flex: 1, marginLeft: 10},
  row: {paddingBottom: 4},
  ImageContainer: {
    borderRadius: 50,
    width: 40,
    height: 40,
    backgroundColor: COLORS['font-color-light'],
    marginRight: 12,
    justifyContent: 'center',
  },
  firstTxt: {
    fontSize: 18,
    color: COLORS['color-text-dark-70'],
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  loader: {
    borderRadius: 50,
    marginRight: 12,
    backgroundColor: COLORS['bg-90-dark'],
    alignItems: 'center',
    justifyContent: 'center',
  },
  dataContainer: {flex: 6, justifyContent: 'space-between'},
  image: {width: 40, height: 40, borderRadius: 40},
  txtName: {
    fontSize: 18,
    fontWeight: '600',
  },
  statusContainer: {flexDirection: 'row', alignItems: 'center'},
  divider: {
    borderColor: COLORS['font-color-light'],
    borderWidth: 0.5,
    marginHorizontal: 6,
    height: 10,
  },
  txtStatus: {
    fontSize: 12,
    color: COLORS['font-color-light'],
    fontWeight: '500',
  },
  txtType: {
    fontSize: 12,
    color: COLORS['font-color-light'],
    fontWeight: '500',
  },
  cardArrow: {
    flex: 0.8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusIndicator: {
    width: 5,
    height: 5,
    borderRadius: 50,
    marginRight: 6,
  },
  btnContainer: {
    backgroundColor: COLORS.button_blue,
    height: 50,
    marginHorizontal: 12,
    padding: 12,
    borderRadius: 10,
    marginBottom: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnView: {
    height: 84,
    paddingTop: 15,
  },
  btnText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS['white'],
  },
  goodTillcancelView: {
    flexDirection: 'row',
    marginTop: 20,
    paddingHorizontal: 7,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  goodTillcancelTextView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  goodTillCancelText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS['white'],
    right: 10,
  },
  toggleView: {
    padding: 2,
    paddingHorizontal: 5,
    borderRadius: 12,
    width: 40,
    height: 20,
    justifyContent: 'center',
  },
  toggleButton: {
    backgroundColor: COLORS['white'],
    width: 12,
    height: 12,
    borderRadius: 12,
  },
  formContainer: {
    height: 510,
    borderRadius: 12,
  },
  formHeader: {
    width: '100%',
    height: '10%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 15,
    flexDirection: 'row',
  },
  headingTxt: {fontSize: 16, fontWeight: '600', flex: 1.5, textAlign: 'right'},
  formInputContainer: {flex: 5, padding: 15},
  inputWrapper: {flexDirection: 'row'},
  firstInput: {paddingBottom: 0, flex: 1},
  closeBtn: {
    textAlign: 'right',
    paddingRight: 20,
    fontWeight: '600',
    fontSize: 17,
  },
  keyTxt: {
    fontSize: 12,
    fontWeight: '500',
    color: '#A2A7B8',
    paddingBottom: 6,
  },
  inputContainer: {fontSize: 12, fontWeight: '500', color: '#A2A7B8'},
  inputField: {
    paddingVertical: Platform.OS === 'ios' ? 17 : 12,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderRadius: 8,
  },
  errorMessage: {
    color: COLORS['color-red'],
    fontWeight: '500',
    marginTop: 4,
  },
  head: {
    alignItems: 'center',
    alignContent: 'center',
    flexDirection: 'row',
    borderWidth: 1,
    width: '100%',
    height: 55,
    paddingLeft: 12,
    borderRadius: 8,
    borderColor: COLORS['font-color-light'],
  },
  countrySelect: {
    width: 80,
    position: 'absolute',
    flexDirection: 'row',
    height: 30,
    justifyContent: 'center',
    paddingHorizontal: 30,
    marginHorizontal: 15,
  },
  verticalLine: {
    marginLeft: 15,
    borderRightWidth: 1,
    borderRightColor: COLORS['btn-cancel'],
  },
  countryCode: {
    position: 'absolute',
    left: 110,
    color: COLORS['bg-80-light'],
  },
  loginInput: {
    color: COLORS['bg-90-light'],
    marginTop: 1.5,
    marginLeft: 135,
    paddingLeft: 40,
    borderBottomEndRadius: 12,
    borderTopEndRadius: 12,
    width: '70%',
  },
  footerContainer: {
    paddingTop: 20,
    borderTopWidth: 1,
  },
});

export const pickerSelectStylesNew = StyleSheet.create({
  inputIOS: {
    borderRadius: 6,
    width: '100%',
    padding: 10,
    color: COLORS['white'],
    fontSize: 16,
  },
  inputAndroid: {
    borderRadius: 6,
    width: '100%',
    padding: 10,
    color: COLORS['white'],
    fontSize: 18,
  },
});

export const pickerSelectStyles = StyleSheet.create({
  inputIOS: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 0,
    borderRadius: 6,
    width: '100%',
    padding: 12,
    color: COLORS['black'],
    fontSize: 16,
    borderColor: 'transparent',
  },
  inputAndroid: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderRadius: 6,
    width: '100%',
    padding: 12,
    color: COLORS['black'],
    fontSize: 16,
    borderColor: 'transparent',
  },
});
