import {Platform, StyleSheet} from 'react-native';
import {COLORS} from '../../../../../assets';

export const coOwnersDetailsStyles = StyleSheet.create({
  container: {padding: 16, height:Platform.OS == 'android' ? '77%': '70%'},
  profileCard: {
    width: '100%',
    height:Platform.OS == 'ios' ? '100%' : "92%" ,
    borderRadius: 8,
    padding: 10,
  },
  txtKeys: {
    color: COLORS['font-color-light'],
    fontWeight: '500',
  },
  details: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS['font-color-light'],
  },
  detailsLast: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 14,
  },
  txtValue: {
    fontWeight: '500',
  },
  statusIndicator: {
    width: 5,
    height: 5,
    borderRadius: 50,
    marginRight: 6,
  },
  firstTxt: {
    fontSize: 18,
    color: COLORS['color-text-dark-70'],
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  ImageContainer: {
    borderRadius: 50,
    width: 90,
    height: 90,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerContainer: {
    height: '50%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerNameTxt: {
    fontSize: 18,
    fontWeight: '600',
    marginTop: 20,
  },
  AccountID: {
    fontSize: 12,
    fontWeight: '600',
    marginTop: 8,
    color: "#878C99",
  },
  detailContainer: {height: '50%'},
  statusContainer: {
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  image: {width: 90, height: 90, borderRadius: 90},
  removeMainContainer: {flex: 1, alignItems: 'center'},
  removeConfirmationContainer: {
    width: '100%',
    height: 30,
    marginTop: 30,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  cancelBtn: {
    width: 40,
    height: 40,
    margin: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmationContainer: {
    height: 250,
    width: 300,
    justifyContent: 'center',
    marginTop: '40%',
  },
  cancelHeadingTxt: {
    fontWeight: '400',
    fontSize: 12,
    textAlign: 'center',
  },
  cancelDescTxt: {
    fontWeight: '600',
    fontSize: 12,
    textAlign: 'center',
  },
  cancelBtnContainer: {
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'space-evenly',
    marginTop: 25,
  },
  cancelContainer: {
    paddingHorizontal: 24,
    paddingVertical: 14,
    width: 144,
    alignItems: 'center',
    borderRadius: 8,
  },
  removeContainer: {
    paddingHorizontal: 24,
    paddingVertical: 14,
    width: 144,
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: COLORS['color-red'],
  },
  actionsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
    marginHorizontal: 20,
  },
  actionTxt: {
    flex: 6,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
    color: COLORS['color-text-dark-100'],
  },
  removePopBtn: {
    flexDirection: 'row',
    width: '92%',
    backgroundColor: COLORS['color-bg-dark-80'],
    height: 60,
    marginBottom: 20,
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
    alignSelf: 'center',
  },
  removePopTxt: {
    color: COLORS['color-red'],
    marginLeft: 15,
    fontSize: 16,
    fontWeight: '400',
  },
});
