import {StyleSheet} from 'react-native';
import {COLORS} from '../../../../assets';

export const OrderOptionsStyles = StyleSheet.create({
  detailContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: COLORS['color-border-dark-100'],
    borderBottomWidth: 1,
    paddingVertical: 16,
    paddingHorizontal: 10,
  },
  imageContainer: {
    backgroundColor: COLORS['color-bg-dark-90'],
    height: 40,
    width: 40,
    borderRadius: 24,
    marginRight: 8,
  },
  image: {
    height: 40,
    width: 40,
    borderRadius: 24,
  },
  details: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  symbol: {
    flex: 0.7,
    flexDirection: 'row',
    alignItems: 'center',
  },
  symbolTxt: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS['white'],
  },
  nameTxt: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS['color-text-dark-70'],
  },
  priceTxt: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS['white'],
  },
  amountDetails: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  quantityTxt: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS['color-text-dark-80'],
  },
  listContainer: {
    flex: 1,
  },
  row: {
    flexDirection: 'row',
  },
  amount: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS['color-text-dark-60'],
  },
  amountTxt: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS['color-text-dark-80'],
  },
  dateDetailContainer: {
    flex: 0.3,
    alignItems: 'flex-end',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timeTxt: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS['color-text-dark-70'],
    marginLeft: 4,
  },
  categoryTxt: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS['color-text-dark-70'],
  },
  typeBuy: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS['color-green'],
  },
  typeSell: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS['color-red'],
  },
  dot: {
    width: 4,
    height: 4,
    backgroundColor: COLORS['font-color-light'],
    borderRadius: 4,
    marginLeft: 8,
    marginRight: 8,
  },
  assetType: {
    backgroundColor: COLORS['color-bg-dark-90'],
    height: 24,
    borderRadius: 4,
    marginTop: 4,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginRight: 8,
  },
  txnType: {
    backgroundColor: COLORS['color-bg-dark-90'],
    height: 24,
    borderRadius: 4,
    marginTop: 4,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  cancelBtn: {
    flex: 1,
    minWidth: 80,
    width: '20%',
    backgroundColor: COLORS['color-bg-dark-80'],
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelTxt: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS['color-text-dark-70'],
  },
  modifyBtn: {
    flex: 1,
    minWidth: 80,
    width: '20%',
    backgroundColor: COLORS['primary-light'],
    alignItems: 'center',
    justifyContent: 'center',
  },
  modifyTxt: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS['white'],
  },
  containerBtn: {
    // height: 80,
    flexDirection: 'row',
    flex: 1,
    paddingVertical: 16,
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  cancel: {
    flex: 0.48,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS['color-transparent-dark-white'],
    borderRadius: 8,
  },
  cancelText: {
    color: COLORS['color-text-dark-80'],
    fontSize: 14,
    fontWeight: '500',
  },
  modify: {
    flex: 0.48,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS['primary-dark'],
    borderRadius: 8,
  },
  modifyText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS['white'],
  },
});
