export const CURRENCIES = [
    { label: 'ARS (Argentine Peso)', value: 'ARS' },
    { label: 'AUD (Australian Dollar)', value: 'AUD' },
    { label: 'BHD (Bahraini Dinar)', value: 'BHD' },
    { label: 'BRL (Brazilian Real)', value: 'BRL' },
    { label: 'CAD (Canadian Dollar)', value: 'CAD' },
    { label: 'CNY (Chinese Yuan (offshore))', value: 'CNY' },
    { label: 'COP (Colombian Peso)', value: 'COP' },
    { label: 'CRC (Costa Rican Colón)', value: 'CRC' },
    { label: 'HRK (Croatian Kuna)', value: 'HRK' },
    { label: 'CZK (Czech Koruna)', value: 'CZK' },
    { label: 'DKK (Danish Krone)', value: 'DKK' },
    { label: 'HKD (Hong Kong Dollar)', value: 'HKD' },
    { label: 'HUF (Hungarian Forint)', value: 'HUF' },
    { label: 'ISK (Icelandic Króna)', value: 'ISK' },
    { label: 'INR (Indian Rupee)', value: 'INR' },
    { label: 'IDR (Indonesian Rupiah)', value: 'IDR' },
    { label: 'ILS (Israeli New Shekel)', value: 'ILS' },
    { label: 'JPY (Japanese Yen)', value: 'JPY' },
    { label: 'MYR (Malaysian Ringgit)', value: 'MYR' },
    { label: 'MXN (Mexican Peso)', value: 'MXN' },
    { label: 'ANG (Netherlands Antillean Guilder)', value: 'ANG' },
    { label: 'NZD (New Zealand Dollar)', value: 'NZD' },
    { label: 'NOK (Norwegian Krone)', value: 'NOK' },
    { label: 'OMR (Omani Rial)', value: 'OMR' },
    { label: 'PHP (Philippine peso)', value: 'PHP' },
    { label: 'PLN (Poland Złoty)', value: 'PLN' },
    { label: 'GBP (Pound sterling)', value: 'GBP' },
    { label: 'QAR (Qatari Rial)', value: 'QAR' },
    { label: 'SAR (Saudi Riyal)', value: 'SAR' },
    { label: 'SGD (Singapore Dollar)', value: 'SGD' },
    { label: 'KRW (South Korean won)', value: 'KRW' },
    { label: 'SEK (Swedish Krona)', value: 'SEK' },
    { label: 'CHF (Swiss Franc)', value: 'CHF' },
    { label: 'THB (Thai Baht)', value: 'THB' },
    { label: 'UAH (Ukrainian hryvnia)', value: 'UAH' },
    { label: 'AED (United Arab Emirates Dirham)', value: 'AED' },
    { label: 'USD (United States Dollar)', value: 'USD' },
    { label: 'EUR (Euro)', value: 'EUR' },
    ];
    