import {StyleSheet} from 'react-native';
import {COLORS} from '../../../../../../assets';

export const style = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {flexDirection: 'row', padding: 4, alignItems: 'center'},
  footerWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
  },
  borderLine: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 6,
    alignSelf: 'center',
    borderStyle: 'dashed',
    borderWidth: 1,
  },
  subText: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 24,
    paddingHorizontal: 8,
  },
  headerText: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 24,
    flex: 1,
  },
  btnText: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    color: COLORS['white'],
  },
  btnContainer: {
    backgroundColor: COLORS['color-red'],
    height: 50,
    marginHorizontal: 4,
    padding: 12,
    borderRadius: 10,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 40,
    width: 40,
    padding: 10,
    borderRadius: 20,
    marginRight: 8,
  },
  uploadContainer: {
    height: '30%',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: COLORS['color-border-dark-90'],
  },
  uploadBox: {justifyContent: 'center', alignItems: 'center'},
  browseTxt: {
    color: COLORS['primary-dark'],
    fontSize: 14,
    fontWeight: '600',
    marginVertical: 10,
  },
  fileTxt: {fontSize: 14, fontWeight: '500'},
  supportTxt: {
    color: COLORS['color-text-light-50'],
    fontSize: 14,
    fontWeight: '500',
  },
  removeMainContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeConfirmationContainer: {
    width: '100%',
    height: 30,
    marginTop: 30,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  cancelBtn: {
    width: 40,
    height: 40,
    margin: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelBtnText: {
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 20,
  },
  confirmationContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelHeadingTxt: {
    fontWeight: '400',
    fontSize: 12,
    textAlign: 'center',
  },
  cancelDescTxt: {
    fontWeight: '600',
    fontSize: 12,
    textAlign: 'center',
    lineHeight: 24,
  },
  cancelBtnContainer: {
    flexDirection: 'row',
  },
  cancelContainer: {
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    paddingVertical: 12,
  },
  removeContainer: {
    paddingVertical: 12,
    alignSelf: 'center',
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: COLORS['color-red'],
  },
  actionsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
    marginHorizontal: 20,
  },
  actionTxt: {
    flex: 6,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
    color: COLORS['color-text-dark-100'],
  },
  removePopBtn: {
    flexDirection: 'row',
    width: '92%',
    backgroundColor: COLORS['color-bg-dark-80'],
    height: 60,
    marginBottom: 20,
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
    alignSelf: 'center',
  },
  removePopTxt: {
    color: COLORS['color-red'],
    marginLeft: 15,
    fontSize: 16,
    fontWeight: '400',
  },
  moadlheader: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
    marginTop: 24,
  },
  textContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  docContainer: {
    flexDirection: 'row',
    paddingVertical: 4,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  headerSection: {
    marginBottom: 10,
    paddingHorizontal: 16,
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
});
